apiVersion: apps/v1
kind: Service
metadata:
  name: {{ .Values.appName }}
specs:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}